# Generated by Django 2.2 on 2020-07-23 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='country Code')),
                ('email_address', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Mobile Number')),
                ('mobile_number_verify', models.BooleanField(default=False, verbose_name='Mobile number verify')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_name', models.TextField(unique=True, verbose_name='User Name')),
                ('accepting_terms', models.BooleanField(default=False, verbose_name='Terms & Condition')),
                ('device_id', models.TextField(verbose_name='Device id')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About me')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender')),
                ('image', models.TextField(blank=True, null=True, verbose_name='image')),
                ('device_type', models.CharField(choices=[('Ios', 'Ios'), ('Android', 'Android')], default='Android', max_length=20, verbose_name='Device Type')),
                ('social_type', models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google')], default='Google', max_length=30, verbose_name='Social Type')),
                ('type_of_Account', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20, verbose_name='Type of Account')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('otp', models.CharField(blank=True, max_length=7, null=True, verbose_name='OTP')),
                ('is_online', models.BooleanField(default=False, verbose_name='User is online')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
